/**:
  ros__parameters:
    use_sim_time: False
    # some case "ros2 run joy joy_enumerate_devices" to get ID and Joystick Device Name use for device_id and device_name

    # The joystick device to use. ros2 run joy joy_enumerate_devices wil list the attached devices.
    # (int, default: 0)
    device_id: 0

    # The joystick name to use. This can be useful when multiple different joysticks are attached.
    # If both device_name and device_id are specified, device_name takes precedence.
    # (string, default: "")
    device_name: ""

    # Amount by which the joystick has to move before it is considered to be off-center.
    # This parameter is specified relative to an axis normalized between -1 and 1.
    # Thus, 0.1 means that the joystick has to move 10% of the way to the edge of an axis's range before that axis will output a non-zero value.
    # (double, default: 0.05)
    deadzone: 0.01

    # Rate in Hz at which a joystick that has a non-changing state will resend the previously sent message.
    # If set to 0.0, autorepeat will be disabled, meaning joy messages will only be published when the joystick changes.
    # Cannot be larger than 1000.0.
    # (double, default: 20.0)
    autorepeat_rate: 20.0

    # Whether buttons are "sticky". If this is false (the default),
    # then a button press will result in a 1 being output,
    # and a button release will result in a 0 being output.
    # If this is true, then a button press will toggle the current state of the button,
    # and a button release will do nothing. Thus, hitting the button while it is currently 0 will switch it to 1,
    # and keep it at 1 until the button is pressed again.
    # (bool, default: false)
    sticky_buttons: False

    # The number of milliseconds to wait after an axis event before publishing a message. 
    # Since the kernel sends an event for every change, this can significantly reduce the number of messages published. 
    # Setting it to 0 disables this behavior.
    # The default of 1 ms is a good compromise between message delays and number of messages published.
    # (int, default: 1)
    coalesce_interval_ms: 1

    

