/**:
  ros__parameters:
    use_sim_time: False
    port: /dev/ydlidar
    ignore_array: ""
    frame_id: lidar_link #laser_frame
    baudrate: 230400
    lidar_type: 1
    device_type: 0
    sample_rate: 1 #9
    abnormal_check_count: 1
    fixed_resolution: true
    reversion: false #true
    inverted: true
    auto_reconnect: true
    isSingleChannel: false
    intensity: true
    support_motor_dtr: true
    angle_max: 110.0 #180.0
    angle_min: -110.0 #-180.0
    range_max: 15.0 #64.0
    range_min: 0.01 #0.1
    frequency: 10.0
    invalid_range_is_inf: false